# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20131003184000) do

  create_table "cart_items", :force => true do |t|
    t.string   "product_name"
    t.string   "product_id"
    t.string   "product_source"
    t.string   "product_image"
    t.string   "product_category"
    t.string   "product_referral_link"
    t.integer  "user_id"
    t.datetime "created_at",            :null => false
    t.datetime "updated_at",            :null => false
    t.string   "product_price"
  end

  create_table "medleys", :force => true do |t|
    t.string   "title"
    t.text     "description"
    t.string   "category"
    t.integer  "votes"
    t.string   "i1_id"
    t.string   "i1_source"
    t.string   "i1_title"
    t.string   "i1_custom_title"
    t.string   "i1_price"
    t.string   "i1_img_small"
    t.string   "i1_img_big"
    t.string   "i1_category"
    t.string   "i1_link"
    t.integer  "i1_x"
    t.integer  "i1_y"
    t.integer  "i1_c"
    t.integer  "i1_r"
    t.string   "i2_id"
    t.string   "i2_source"
    t.string   "i2_title"
    t.string   "i2_custom_title"
    t.string   "i2_price"
    t.string   "i2_img_small"
    t.string   "i2_img_big"
    t.string   "i2_category"
    t.string   "i2_link"
    t.integer  "i2_x"
    t.integer  "i2_y"
    t.integer  "i2_c"
    t.integer  "i2_r"
    t.string   "i3_id"
    t.string   "i3_source"
    t.string   "i3_title"
    t.string   "i3_custom_title"
    t.string   "i3_price"
    t.string   "i3_img_small"
    t.string   "i3_img_big"
    t.string   "i3_category"
    t.string   "i3_link"
    t.integer  "i3_x"
    t.integer  "i3_y"
    t.integer  "i3_c"
    t.integer  "i3_r"
    t.string   "i4_id"
    t.string   "i4_source"
    t.string   "i4_title"
    t.string   "i4_custom_title"
    t.string   "i4_price"
    t.string   "i4_img_small"
    t.string   "i4_img_big"
    t.string   "i4_category"
    t.string   "i4_link"
    t.integer  "i4_x"
    t.integer  "i4_y"
    t.integer  "i4_c"
    t.integer  "i4_r"
    t.string   "i5_id"
    t.string   "i5_source"
    t.string   "i5_title"
    t.string   "i5_custom_title"
    t.string   "i5_price"
    t.string   "i5_img_small"
    t.string   "i5_img_big"
    t.string   "i5_category"
    t.string   "i5_link"
    t.integer  "i5_x"
    t.integer  "i5_y"
    t.integer  "i5_c"
    t.integer  "i5_r"
    t.string   "i6_id"
    t.string   "i6_source"
    t.string   "i6_title"
    t.string   "i6_custom_title"
    t.string   "i6_price"
    t.string   "i6_img_small"
    t.string   "i6_img_big"
    t.string   "i6_category"
    t.string   "i6_link"
    t.integer  "i6_x"
    t.integer  "i6_y"
    t.integer  "i6_c"
    t.integer  "i6_r"
    t.string   "i7_id"
    t.string   "i7_source"
    t.string   "i7_title"
    t.string   "i7_custom_title"
    t.string   "i7_price"
    t.string   "i7_img_small"
    t.string   "i7_img_big"
    t.string   "i7_category"
    t.string   "i7_link"
    t.integer  "i7_x"
    t.integer  "i7_y"
    t.integer  "i7_c"
    t.integer  "i7_r"
    t.string   "i8_id"
    t.string   "i8_source"
    t.string   "i8_title"
    t.string   "i8_custom_title"
    t.string   "i8_price"
    t.string   "i8_img_small"
    t.string   "i8_img_big"
    t.string   "i8_category"
    t.string   "i8_link"
    t.integer  "i8_x"
    t.integer  "i8_y"
    t.integer  "i8_c"
    t.integer  "i8_r"
    t.string   "i9_id"
    t.string   "i9_source"
    t.string   "i9_title"
    t.string   "i9_custom_title"
    t.string   "i9_price"
    t.string   "i9_img_small"
    t.string   "i9_img_big"
    t.string   "i9_category"
    t.string   "i9_link"
    t.integer  "i9_x"
    t.integer  "i9_y"
    t.integer  "i9_c"
    t.integer  "i9_r"
    t.string   "i10_id"
    t.string   "i10_source"
    t.string   "i10_title"
    t.string   "i10_custom_title"
    t.string   "i10_price"
    t.string   "i10_img_small"
    t.string   "i10_img_big"
    t.string   "i10_category"
    t.string   "i10_link"
    t.integer  "i10_x"
    t.integer  "i10_y"
    t.integer  "i10_c"
    t.integer  "i10_r"
    t.string   "i11_id"
    t.string   "i11_source"
    t.string   "i11_title"
    t.string   "i11_custom_title"
    t.string   "i11_price"
    t.string   "i11_img_small"
    t.string   "i11_img_big"
    t.string   "i11_category"
    t.string   "i11_link"
    t.integer  "i11_x"
    t.integer  "i11_y"
    t.integer  "i11_c"
    t.integer  "i11_r"
    t.string   "i12_id"
    t.string   "i12_source"
    t.string   "i12_title"
    t.string   "i12_custom_title"
    t.string   "i12_price"
    t.string   "i12_img_small"
    t.string   "i12_img_big"
    t.string   "i12_category"
    t.string   "i12_link"
    t.integer  "i12_x"
    t.integer  "i12_y"
    t.integer  "i12_c"
    t.integer  "i12_r"
    t.string   "i13_id"
    t.string   "i13_source"
    t.string   "i13_title"
    t.string   "i13_custom_title"
    t.string   "i13_price"
    t.string   "i13_img_small"
    t.string   "i13_img_big"
    t.string   "i13_category"
    t.string   "i13_link"
    t.integer  "i13_x"
    t.integer  "i13_y"
    t.integer  "i13_c"
    t.integer  "i13_r"
    t.string   "i14_id"
    t.string   "i14_source"
    t.string   "i14_title"
    t.string   "i14_custom_title"
    t.string   "i14_price"
    t.string   "i14_img_small"
    t.string   "i14_img_big"
    t.string   "i14_category"
    t.string   "i14_link"
    t.integer  "i14_x"
    t.integer  "i14_y"
    t.integer  "i14_c"
    t.integer  "i14_r"
    t.string   "i15_id"
    t.string   "i15_source"
    t.string   "i15_title"
    t.string   "i15_custom_title"
    t.string   "i15_price"
    t.string   "i15_img_small"
    t.string   "i15_img_big"
    t.string   "i15_category"
    t.string   "i15_link"
    t.integer  "i15_x"
    t.integer  "i15_y"
    t.integer  "i15_c"
    t.integer  "i15_r"
    t.string   "i16_id"
    t.string   "i16_source"
    t.string   "i16_title"
    t.string   "i16_custom_title"
    t.string   "i16_price"
    t.string   "i16_img_small"
    t.string   "i16_img_big"
    t.string   "i16_category"
    t.string   "i16_link"
    t.integer  "i16_x"
    t.integer  "i16_y"
    t.integer  "i16_c"
    t.integer  "i16_r"
    t.datetime "created_at",                      :null => false
    t.datetime "updated_at",                      :null => false
    t.integer  "remix_of"
    t.integer  "tag_1_id"
    t.integer  "tag_2_id"
    t.integer  "tag_3_id"
    t.integer  "user_id",          :default => 1
  end

  create_table "newsletter_subscribers", :force => true do |t|
    t.string   "email"
    t.string   "first_name"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

  create_table "tags", :force => true do |t|
    t.string   "tag"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

  create_table "users", :force => true do |t|
    t.string   "email",                                 :default => "",            :null => false
    t.string   "encrypted_password",     :limit => 128, :default => "",            :null => false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",                         :default => 0
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                                                       :null => false
    t.datetime "updated_at",                                                       :null => false
    t.string   "username"
    t.string   "affiliate_id",                          :default => "medley01-20", :null => false
  end

  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["reset_password_token"], :name => "index_users_on_reset_password_token", :unique => true

end
